### ISSUE TITLE
Not working with Episerver 11

### ISSUE THREAD

**Issue by lhutz** [valdisiljuconoks/MvcAreasForEPiServer#2]
Hey,

There are some breaking changes in Episerver 11 so when implementing this while on Episerver 11 it gives an error saying that is cannot find InitializationModule.
Together with a colleague we copied this whole git in our existing project and we got it to work. I've cloned this git locally and applied the changes in the epi11 branch. However, with us this caused an error when logging in on /episerver/cms with AD.

Would you mind having a look at my pull request and check whether you also get that error when logging in?

Cheers,
Lindy

**Comment by lhutz** [comment]
Update: I can't commit because I don't have access. So basically what I did  was branch from epi10,  change the TargetFrameworkVersion to 4.6.1 and update all packages to the latest.

**Comment by valdisiljuconoks** [comment]
Hi,

You can definitely do all the commits in your private fork and then can do pull request to the origin.

It will be easier to maintain and test.

Think I don't have proper AD at hand to test it out..

What errors you see?


Get Outlook for Android

________________________________

**Comment by lhutz** [comment]
Okay, done!

My colleague got an error when he tried logging in to "/episerver" with his Windows credentials. It said that the user could not be found.

**Comment by valdisiljuconoks** [comment]
Hi,

You sure that it's related to Mvc areas?


Get Outlook for Android

________________________________

**Comment by lhutz** [comment]
My colleague got that error. I just tried it out myself and I cannot reproduce. Added a minor change and it works like a charm now 😄

**Comment by valdisiljuconoks** [comment]
Wait for 4.0 version of the package

**Comment by lhutz** [comment]
Awesome 😎
